function formatPrice(value) {
  const n =
    typeof value === "number"
      ? value
      : parseFloat(String(value).replace(/[^0-9.-]/g, ""));
  if (Number.isNaN(n)) return "$0.00";
  return `$${n.toFixed(2)}`;
}

function parsePrice(value) {
  const n =
    typeof value === "number"
      ? value
      : parseFloat(String(value).replace(/[^0-9.-]/g, ""));
  return Number.isNaN(n) ? 0 : n;
}

const products = [
  {
    id: 1,
    title: "milk and honey",
    author: "Rupi Kaur",
    price: 12.99,
    img: "/Assets/pic1.jpg",
    rating: 4.7,
    featured: true,
    bestseller: false,
    desc: "A collection of poetry and prose about love, healing, and self-empowerment from Instagram sensation Rupi Kaur.",
  },
  {
    id: 2,
    title: "Will You Stay",
    author: "Christina Lauren",
    price: 14.99,
    img: "/Assets/pic2.jpg",
    rating: 4.3,
    featured: true,
    bestseller: false,
    desc: "A moving novel about love, loss, and the choices that keep us together or tear us apart.",
  },
  {
    id: 3,
    title: "Sculpture",
    author: "Megan Shepherd",
    price: 11.49,
    img: "/Assets/pic3.jpg",
    rating: 4.1,
    featured: true,
    bestseller: false,
    desc: "A darkly magical tale of art, ambition, and the price of creation.",
  },
  {
    id: 4,
    title: "Sign Of Grow Up",
    author: "Abhijit Bhaduri",
    price: 13.99,
    img: "/Assets/pic4.webp",
    rating: 4.0,
    featured: true,
    bestseller: false,
    desc: "A practical guide to maturing faster in career and life.",
  },
  {
    id: 5,
    title: "The Two Of Us",
    author: "Kathryn Smith",
    price: 15.99,
    img: "/Assets/pic5.jpg",
    rating: 4.2,
    featured: true,
    bestseller: false,
    desc: "An emotional story exploring how two souls find each other through life's twists.",
  },
  {
    id: 6,
    title: "This could be Home",
    author: "Kasouie",
    price: 10.99,
    img: "/Assets/pic6.webp",
    rating: 3.9,
    featured: true,
    bestseller: false,
    desc: "A heartfelt exploration of belonging and what makes a place feel like home.",
  },
  {
    id: 7,
    title: "The girl on the Train",
    author: "Paula Hawkins",
    price: 16.99,
    img: "/Assets/pic7.webp",
    rating: 4.5,
    featured: true,
    bestseller: false,
    desc: "A psychological thriller about a commuter who becomes entangled in a mystery.",
  },
  {
    id: 8,
    title: "The Art Of Being Alone",
    author: "Deepak Chopra",
    price: 12.49,
    img: "/Assets/pic8.webp",
    rating: 4.0,
    featured: true,
    bestseller: false,
    desc: "Guidance on finding peace and purpose in solitude.",
  },
  {
    id: 9,
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    price: 13.99,
    img: "/Assets/pic1.jpg",
    rating: 4.8,
    featured: true,
    bestseller: false,
    desc: "A coming-of-age murder mystery set in the marshes of North Carolina.",
  },
  {
    id: 10,
    title: "Becoming",
    author: "Michelle Obama",
    price: 18.99,
    img: "/Assets/pic2.jpg",
    rating: 4.9,
    featured: true,
    bestseller: false,
    desc: "A candid memoir from the former First Lady of the United States.",
  },
  {
    id: 11,
    title: "The Midnight Library",
    author: "Matt Haig",
    price: 14.49,
    img: "/Assets/pic3.jpg",
    rating: 4.4,
    featured: true,
    bestseller: false,
    desc: "A novel about the infinite possibilities of the life you could have lived.",
  },
  {
    id: 12,
    title: "Atomic Habits",
    author: "James Clear",
    price: 16.99,
    img: "/Assets/pic4.webp",
    rating: 4.9,
    featured: true,
    bestseller: true,
    desc: "An easy and proven way to build good habits and break bad ones.",
  },
  {
    id: 13,
    title: "Project Hail Mary",
    author: "Andy Weir",
    price: 16.49,
    img: "/Assets/pic5.jpg",
    rating: 4.6,
    featured: true,
    bestseller: false,
    desc: "A lone astronaut must save Earth's climate in this sci-fi thriller.",
  },
  {
    id: 14,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    price: 12.99,
    img: "/Assets/pic6.webp",
    rating: 4.5,
    featured: true,
    bestseller: false,
    desc: "A woman's act of violence against her husband, and the therapist obsessed with uncovering why.",
  },
  {
    id: 15,
    title: "It Ends with Us",
    author: "Colleen Hoover",
    price: 14.99,
    img: "/Assets/pic7.webp",
    rating: 4.7,
    featured: true,
    bestseller: false,
    desc: "A powerful novel about love, trauma, and the courage to break cycles.",
  },
  {
    id: 16,
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    price: 17.49,
    img: "/Assets/pic8.webp",
    rating: 4.3,
    featured: true,
    bestseller: false,
    desc: "A guide to understanding and wielding power throughout history and life.",
  },
  {
    id: 17,
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 14.99,
    img: "/Assets/pic1.jpg",
    rating: 4.8,
    featured: false,
    bestseller: true,
    desc: "A shepherd boy's journey to discover the world's greatest treasure.",
  },
  {
    id: 18,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: 15.49,
    img: "/Assets/pic2.jpg",
    rating: 4.7,
    featured: false,
    bestseller: true,
    desc: "Timeless lessons about the psychology of money, investing, and wealth.",
  },
  {
    id: 19,
    title: "Deep Work",
    author: "Cal Newport",
    price: 13.99,
    img: "/Assets/pic3.jpg",
    rating: 4.6,
    featured: false,
    bestseller: true,
    desc: "A guide to cultivating focus and producing high-quality work in a distracted world.",
  },
  {
    id: 20,
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    price: 12.99,
    img: "/Assets/pic4.webp",
    rating: 4.5,
    featured: false,
    bestseller: true,
    desc: "A classic self-help book on achievement and personal development.",
  },
  {
    id: 21,
    title: "The 5 AM Club",
    author: "Robin Sharma",
    price: 14.49,
    img: "/Assets/pic5.jpg",
    rating: 4.4,
    featured: false,
    bestseller: true,
    desc: "Reprogram your mornings to win at the day and own your life.",
  },
  {
    id: 22,
    title: "Zero to One",
    author: "Peter Thiel",
    price: 17.99,
    img: "/Assets/pic6.webp",
    rating: 4.7,
    featured: false,
    bestseller: true,
    desc: "Notes on startups and how to build the future, from PayPal co-founder Peter Thiel.",
  },
  {
    id: 23,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    price: 13.49,
    img: "/Assets/pic7.webp",
    rating: 4.6,
    featured: false,
    bestseller: true,
    desc: "A counterintuitive approach to living a good life by focusing on what truly matters.",
  },
];

export default products;
export const featuredBooks = products.filter((p) => p.featured);
export const bestsellers = products.filter((p) => p.bestseller);
export { formatPrice, parsePrice };
